### PR TITLE
Publish travel posts

### PR DESCRIPTION
**Pull request by mdjnewman**
@DanielPNewman I finally got around to writing up all the travel emails 😁 

They're on the `master` branch as drafts at the moment, this PR publishes them all.

I've set up a 'staging' instance of the site at https://mdjnewman.me/mdjnewman.github.io-staging/all-posts/ - would you mind sanity checking the links/content?

The posts are:

https://mdjnewman.me/mdjnewman.github.io-staging/2016/02/johannesburg
https://mdjnewman.me/mdjnewman.github.io-staging/2016/07/europe
https://mdjnewman.me/mdjnewman.github.io-staging/2017/09/denver-rocky-mountains
https://mdjnewman.me/mdjnewman.github.io-staging/2018/04/dallas
https://mdjnewman.me/mdjnewman.github.io-staging/2018/04/miami-keys-everglades
https://mdjnewman.me/mdjnewman.github.io-staging/2018/05/nyc
https://mdjnewman.me/mdjnewman.github.io-staging/2018/05/washington-dc
https://mdjnewman.me/mdjnewman.github.io-staging/2018/05/brown-county-state-park-nashville-in

### CODE REVIEW

**Comment by DanielPNewman** [comment]
Hey bro, just looking at this now :-)

**Comment by DanielPNewman** [comment]
Wow I can't believe that the Denver mint makes coins for China!

**Comment by DanielPNewman** [comment]
Your `_config.yml` says "living in Dallas, Texas (previously Brisbane, Australia)"... you need to update to Florida :-)

**Comment by DanielPNewman** [comment]
One last thing, the links on this feeds page just go to xml , is that right? https://mdjnewman.me/mdjnewman.github.io-staging/feeds/

**Comment by mdjnewman** [comment]
Thanks @DanielPNewman , I [added some notes](https://github.com/mdjnewman/mdjnewman.github.io/pull/2/commits/d05c7a19c97431e6c5e2f526c6a9d47776ca0d77) about RSS to clarify the feeds page.

**Pull request merged**
